# .github/workflows/build.yml
name: Build and release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
          MINIFY: true
          ARCHIVE_NAME: Vulpes-Porto_x86_64-unknown-linux-musl
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
      - name: Make release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automatic Build"
          files: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
